---
version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    post_checkout:
      - git fetch --unshallow || true
python:
  install:
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
