name: Build distribution files

on:
  release:
    types: [published]

jobs:
  test:
    name: Build distribution files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --user build setuptools twine wheel

      - name: Build package
        run: python -m build

      - name: Verify package
        run: twine check --strict dist/*

      - name: Upload package to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          if-no-files-found: error
