name: Packaging

on:
  - push
  - pull_request

jobs:
  test:
    name: Packaging
    runs-on: ubuntu-latest

    env:
      TOXENV: packaging

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox
