name: Packaging

on:
  - push
  - pull_request

jobs:
  test:
    name: Packaging
    runs-on: ubuntu-latest

    env:
      TOXENV: packaging

    steps:
      - name: Install LDAP libs
        run: |
          sudo apt-get update
          # https://www.python-ldap.org/en/latest/installing.html#debian
          sudo apt-get install slapd ldap-utils libldap2-dev libsasl2-dev
          # https://github.com/python-ldap/python-ldap/issues/370
          sudo apt-get install apparmor-utils
          sudo aa-disable /usr/sbin/slapd

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: python -m pip install tox

      - name: Run tests
        run: tox
